### ISSUE TITLE
Replacing the hard-coded wait function on initial page load with something else

### ISSUE THREAD

**Issue by sahil-lalani** [CEREBRUS-MAXIMUS/Surfer-Data#2]
Currently, there is a hard-coded wait function on the initial page load. Instead, we'd rather have a more dynamic and flexible way of checking for page load, whether it's through event listeners or waiting for page elements, thus enhancing the user experience by reducing unnecessary wait times.

**Comment by rafabo7** [comment]
Hi! I would like to contribute, where can I find the mentioned function?

**Comment by sahil-lalani** [comment]
Hi! The function is used at the beginning of all the platform-specific functions (e.g. `notion.js, github.js, twitter.js, etc`) and is defined in `preloadFunctions.js`
