### ISSUE TITLE
Add error handling for platform-specific modules

### ISSUE THREAD

**Issue by sahil-lalani** [CEREBRUS-MAXIMUS/Surfer-Data#3]
Currently, our platform-specific export functions (e.g., notion.js, github.js, etc.) lack robust error handling. This can lead to confusion for users and potentially result in incomplete or failed exports without clear feedback. This can be done through: 1) try-catch blocks and 2) handling different types of errors (page not loaded, internet not working, etc)

**Comment by vr-varad** [comment]
@sahil-lalani I would like to work upon this issue if its open for contributions

**Comment by sahil-lalani** [comment]
@vr-varad Yup it’s open, go for it! Just assigned it to you.
